---
os: "linux"
arch: "amd64"

vip: 192.168.0.200

metallb_version: v0.13.12
lb_range: 192.168.0.210-192.168.0.230
lb_pool_name: first-pool

ansible_become: true
ansible_become_method: sudo
################################################################################
# options to change default values
kube_vip_version: "v0.8.0"
vip_interface: "enp0s3"
rke2_version: "v1.29.4+rke2r1"
rke2_install_dir: "/usr/local/bin"
